 name: first workflow
 
 on: workflow_dispatch
 
 jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
       - name: Print Greeting
         run: |
           echo "Started Workflow"
           echo "Hello World!"
       - name: Print Goodbye
         run: |
           echo "Ending Workflow"
           echo "Done - bye!"
      
